[project]
name = "backend"
version = "0.1.0"
description = "Nothing!!!"
readme = "../README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standart]>=0.128.0",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
    